spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-zsg
server:
  port: 30000
