spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G3qAesQAAJAjF11enJS
      secret-key: VRmciwr0FImtG2b8MIL8woQKbf1yMg
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-zsg
server:
  port: 30000